export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SETUP_REQUEST = 'USER_SETUP_REQUEST';
export const USER_SETUP_SUCCESS = 'USER_SETUP_SUCCESS';
export const USER_SETUP_FAILED = 'USER_SETUP_FAILED';
