export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SETUP_REQUEST = 'USER_SETUP_REQUEST';
export const USER_SETUP_SUCCESS = 'USER_SETUP_SUCCESS';
export const USER_SETUP_FAILED = 'USER_SETUP_FAILED';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
